Repository codebuddies/greetbot, pull requests merged in 2018-03, with the labels that each got.

#31 Merging in bg_refactor
  .config/configstore/update-notifier-npm.json
  .config/configstore/update-notifier-pnpm.json
  package.json
  shrinkwrap.yaml
  src/app/routes/data/events/initialWelcome.js
  src/app/routes/data/interactive/initialResponse.js
  src/app/routes/data/slash/resources/resourcesHelp.js
  src/app/routes/data/slash/welcome/slashWelcome.js
  src/app/routes/data/slash/welcome/welcomeHelp.js
  src/app/routes/endpoints/events/initial.js
  src/app/routes/endpoints/interactive/reminder.js
  src/app/routes/endpoints/slash/resources/resources.js
  src/app/routes/endpoints/slash/welcome/welcome.js
  src/app/routes/slash/resources.js
  src/app/routes/slash/welcome.js
  src/app/util/incomingParser.js
  src/app/util/remind.js
  src/index.js
Labels: ready for review

#30 Update README docs
  LICENSE
  README.md
Labels: feedback needed, in progress

#32 Update LICENSE
  LICENSE
Labels: ready for review

#33 Update package json scripts
  package.json
Labels: chore, ready for review

#42 Setup Local Development with localtunnel and Slack
  .env.example
  README.md
  package.json
  src/config/localtunnel.js
Labels: Discussion Needed, chore, feedback needed, ready for review

#49 Refactor resources template message
  src/app/routes/data/slash/resources/genericResourcesAttachmentTemplate.js
  src/app/routes/endpoints/slash/resources/resources.js
Labels: ready for review

#51 Reduce semver strictness for node
  package.json
Labels: ready for review

#57 Glob resources, and generate a message based on arguments
  package.json
  src/app/routes/data/slash/resources/genericResourcesAttachmentTemplate.js
  src/app/routes/data/slash/resources/messageAttachments/genericAttachment.yml
  src/app/routes/data/slash/resources/messageAttachments/javascript/advanced/effectivejs.yml
  src/app/routes/data/slash/resources/messageAttachments/javascript/advanced/javascriptpatterns.yml
  src/app/routes/data/slash/resources/messageAttachments/javascript/advanced/learningadvancedjs.yml
  src/app/routes/data/slash/resources/messageAttachments/javascript/advanced/wtheventloop.yml
  src/app/routes/data/slash/resources/messageAttachments/javascript/beginner/javascript30.yml
  src/app/routes/data/slash/resources/messageAttachments/javascript/beginner/jstheweirdparts.yml
  src/app/routes/data/slash/resources/messageAttachments/javascript/beginner/watchandcode.yml
  src/app/routes/data/slash/resources/messageAttachments/javascript/beginner/youdontknowjs.yml
  src/app/routes/data/slash/resources/messageAttachments/javascript/intermediate/eloquentjavascript.yml
  src/app/routes/data/slash/resources/messageAttachments/javascript/intermediate/jsthehardparts.yml
  src/app/routes/data/slash/resources/messageAttachments/javascript/intermediate/rithmschool.yml
  src/app/routes/data/slash/resources/messageAttachments/javascript/intermediate/scotchio.yml
  src/app/routes/data/slash/resources/messageAttachments/python/advanced/concurrencyinpython.yml
  src/app/routes/data/slash/resources/messageAttachments/python/advanced/fluentpython.yml
  src/app/routes/data/slash/resources/messageAttachments/python/advanced/magicmethods.yml
  src/app/routes/data/slash/resources/messageAttachments/python/advanced/towerofabstraction.yml
  src/app/routes/data/slash/resources/messageAttachments/python/beginner/automatetheboringstuffvideos.yml
  src/app/routes/data/slash/resources/messageAttachments/python/beginner/pythonmitx6001.yml
  src/app/routes/data/slash/resources/messageAttachments/python/beginner/pythonofficaltutorial.yml
  src/app/routes/data/slash/resources/messageAttachments/python/beginner/thepythongurututorial.yml
  src/app/routes/data/slash/resources/messageAttachments/python/intermediate/builtinsuperheros.yml
  src/app/routes/data/slash/resources/messageAttachments/python/intermediate/effectivepython.yml
  src/app/routes/data/slash/resources/messageAttachments/python/intermediate/intermedatepythonprogramming.yml
  src/app/routes/data/slash/resources/messageAttachments/python/intermediate/mitxpython6002.yml
  src/app/routes/data/slash/resources/messageBodies/javascript/jsa.yml
  src/app/routes/data/slash/resources/messageBodies/javascript/jsb.yml
  src/app/routes/data/slash/resources/messageBodies/javascript/jsm.yml
  src/app/routes/data/slash/resources/messageBodies/python/pya.yml
  src/app/routes/data/slash/resources/messageBodies/python/pyb.yml
  src/app/routes/data/slash/resources/messageBodies/python/pym.yml
  src/app/routes/data/slash/resources/messageTemplates/genericResourcesAttachmentTemplate.js
  src/app/routes/data/slash/resources/messageTemplates/resourcesHelp.js
  src/app/routes/data/slash/resources/messageTemplates/resourcesMessage.js
  src/app/routes/endpoints/slash/resources/resources.js
  src/app/util/incomingParser.js
  src/app/util/sortArguments.js
  src/app/util/ymlFilters.js
  src/app/util/ymlLoader.js
Labels: ready for review
