Repository codebuddies/greetbot, pull requests merged in 2018-04, with the labels that each got.

#66 Update test suites [WIP]
  .eslintrc
  package.json
  src/app/util/incomingParser.js
  src/app/util/sortArguments.js
  src/index.js
  test/.eslintrc
  test/helper.js
  test/incomingParser.test.js
  test/mocha.opts
  test/parser.test.js
  test/routes.test.js
  test/welcome.test.js
Labels: in progress

#68 Adding Dockerfile and docker-compose.test.yml for testing inside docker-cloud.
  Dockerfile
  docker-compose.test.yml
Labels: Discussion Needed

#69 Revert "Adding Dockerfile and docker-compose.test.yml for testing inside docker-cloud."
  Dockerfile
  docker-compose.test.yml
Labels: Discussion Needed, on hold

#64 add resource view helper
  package.json
  src/app/util/groupBy.js
  src/app/util/ymlLoader.js
  src/index.js
  src/views/index.ejs
  src/views/resources/index.ejs
  src/views/resources/partials/edit_form.ejs
  src/views/resources/partials/readonly_form.ejs
  src/views/resources/show.ejs
  test/routes.test.js
Labels: ready for review

#70 Update npm packages
  package.json
Labels: ready for review
